# Generated by Django 4.2.6 on 2023-12-09 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
    ]
