# Generated by Django 4.2.6 on 2024-04-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_students_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='referal_code',
            field=models.CharField(blank=True, choices=[('1011', 'Sales agent'), ('1012', 'Social media advertisments'), ('1013', 'Referred by students'), ('1014', 'Out of home advertisements'), ('1015', 'none')], max_length=30, null=True),
        ),
    ]
