# Generated by Django 4.2.6 on 2023-11-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_staffrecords_studentrecords_delete_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentrecords',
            old_name='department',
            new_name='tutor',
        ),
        migrations.AlterField(
            model_name='staffrecords',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='ParentRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sno', models.IntegerField(default=0)),
                ('number_of_childrens', models.IntegerField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('students_ids', models.ManyToManyField(to='webapp.studentrecords')),
            ],
        ),
    ]
